
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!-- Place this script in the <head> or at the end of the <body> tag -->

<!DOCTYPE html>
<html>
<head>
<title>Orders List</title>
<style>
/* Styles for the table */
body {
	background-image:
		url("https://images.pexels.com/photos/7130555/pexels-photo-7130555.jpeg?auto=compress&cs=tinysrgb&w=600");
	background-size: cover;
	background-repeat: no-repeat;
	margin: 0;
	padding: 0;
	font-family: Arial, sans-serif;
	background-color: #f2f2f2;
}

.navbar {
	background-color: transparent;
	overflow: hidden;
}

.navbar a {
	float: left;
	color: black;
	text-align: center;
	padding: 14px 16px;
	text-decoration: none;
}

.navbar a:hover {
	background-color: #111;
	color: white;
}

.container {
	max-width: 800px;
	margin: 20px auto;
	padding: 20px;
	background-color: #fff;
	border-radius: 5px;
	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
}
.dropdown {
	margin-bottom: 10px;
	position: relative;
}

.dropdown-select {
	padding: 8px;
	border: 1px solid #ccc;
	border-radius: 4px;
	background-color: #fff;
	width: 100%;
	cursor: pointer;
}

.dropdown-menu {
	display: none;
	padding: 5px;
	background-color: #fff;
	border: 1px solid #ccc;
	border-radius: 4px;
	position: absolute;
	top: 100%;
	left: 0;
	width: 100%;
	z-index: 1;
}

.dropdown-menu a {
	display: block;
	padding: 5px;
	text-decoration: none;
	color: #007bff;
}

.dropdown-menu a:hover {
	background-color: #f5f5f5;
}Ss

h1 {
	text-align: center;
}
form {
	margin-bottom: 20px;
}

label {
	display: block;
	margin-bottom: 10px;
	font-weight: bold;
}

select, input[type="text"] {
	width: 100%;
	padding: 10px;
	margin-bottom: 10px;
	border: 1px solid #ccc;
	border-radius: 4px;
}

button {
	background-color: #4CAF50;
	color: white;
	padding: 10px 20px;
	border: none;
	border-radius: 4px;
	cursor: pointer;
}

button:hover {
	background-color: #45a049;
}

table {
	width: 100%;
	border-collapse: collapse;
}

th, td {
	padding: 10px;
	text-align: left;
	border-bottom: 1px solid #ccc;
}

tr:hover {
	background-color: #f5f5f5;
}

.highlight {
	background-color: #f5f5f5;
}

</style>
</head>
<body>
	<div class="navbar">
		<a href="orders">Go Back</a>
	</div>
	<div class="container">
	
	
	 <h1>Total revenue generated: ${totalRevenue}</h1>
		<div class="dropdown">
			<select class="dropdown-select" onchange="handleDropdownChange(this)">
				<option value="#" selected disabled>Filters</option>
				<option value="monthlyRevenue">Monthly revenue</option>
				<option value="quarterlyRevenue">Quarterly revenue</option>
				<option value="annualRevenue">Annual revenue</option>

			</select>
			<div class="dropdown-menu">
				orders</a> 
				<a href="monthlyRevenue">Monthly revenue</a> 
				<a href="quarterlyRevenue">Quarterly revenue</a> 
				<a href="annualRevenue">Annual revenue</a>
			</div>
			<body>
   
    
    <hr>
    <p>Enter Car Name to get Revenue Generated By particular Model</p>
    <form action="/ProdEnquriyManagementSystem/revenueBasedOnName" method="get">
        <label for="carName"></label>
        <input type="text" id="carName" name="carName">
        <button type="submit">Generate Revenue</button>
    </form>
</body>
			<!-- <h1>Monthly Revenue</h1> -->
		<%-- 	<table>
				<tr>
					<th>Month</th>
					<th>Year</th>
					<th>Revenue</th>
				</tr>
				<c:forEach items="${monthlyBillAmount}" var="monthlyAmount">
					<tr>
						<td>${monthlyAmount.month}</td>
						<td>${monthlyAmount.year}</td>
						<td>${monthlyAmount.totalBillAmount}</td>
					</tr>
				</c:forEach>
			</table> --%>
			  
		</div>

		<script>
			// Function to handle the dropdown change event
			function handleDropdownChange(select) {
				const selectedOption = select.value;
				if (selectedOption !== '#') {
					window.location.href = selectedOption;
				}
			}
		</script>
</body>
</html>

